fragment DocParts on Doc {
  __typename
  title
  body
}

fragment SidebarParts on Sidebar {
  __typename
  _warning
  label
  items {
    __typename
    label
    items {
      __typename
      ... on SidebarItemsItemsCategory {
        title
        link
        docLink {
          ... on Doc {
            __typename
            title
            body
          }
          ... on Document {
            _sys {
              filename
              basename
              breadcrumbs
              path
              relativePath
              extension
            }
            id
          }
        }
        items {
          __typename
          ... on SidebarItemsItemsCategoryItemsCategory {
            title
            link
            docLink {
              ... on Doc {
                __typename
                title
                body
              }
              ... on Document {
                _sys {
                  filename
                  basename
                  breadcrumbs
                  path
                  relativePath
                  extension
                }
                id
              }
            }
            items {
              __typename
              ... on SidebarItemsItemsCategoryItemsCategoryItemsCategory {
                title
                link
                docLink {
                  ... on Doc {
                    __typename
                    title
                    body
                  }
                  ... on Document {
                    _sys {
                      filename
                      basename
                      breadcrumbs
                      path
                      relativePath
                      extension
                    }
                    id
                  }
                }
                items {
                  __typename
                  ... on SidebarItemsItemsCategoryItemsCategoryItemsCategoryItemsDoc {
                    document {
                      ... on Doc {
                        __typename
                        title
                        body
                      }
                      ... on Document {
                        _sys {
                          filename
                          basename
                          breadcrumbs
                          path
                          relativePath
                          extension
                        }
                        id
                      }
                    }
                    label
                  }
                  ... on SidebarItemsItemsCategoryItemsCategoryItemsCategoryItemsLink {
                    title
                    href
                  }
                }
              }
              ... on SidebarItemsItemsCategoryItemsCategoryItemsDoc {
                document {
                  ... on Doc {
                    __typename
                    title
                    body
                  }
                  ... on Document {
                    _sys {
                      filename
                      basename
                      breadcrumbs
                      path
                      relativePath
                      extension
                    }
                    id
                  }
                }
                label
              }
              ... on SidebarItemsItemsCategoryItemsCategoryItemsLink {
                title
                href
              }
            }
          }
          ... on SidebarItemsItemsCategoryItemsDoc {
            document {
              ... on Doc {
                __typename
                title
                body
              }
              ... on Document {
                _sys {
                  filename
                  basename
                  breadcrumbs
                  path
                  relativePath
                  extension
                }
                id
              }
            }
            label
          }
          ... on SidebarItemsItemsCategoryItemsLink {
            title
            href
          }
        }
      }
      ... on SidebarItemsItemsDoc {
        document {
          ... on Doc {
            __typename
            title
            body
          }
          ... on Document {
            _sys {
              filename
              basename
              breadcrumbs
              path
              relativePath
              extension
            }
            id
          }
        }
        label
      }
      ... on SidebarItemsItemsLink {
        title
        href
      }
      ... on SidebarItemsItemsDivider {
        title
      }
    }
  }
}

fragment QuicklinkParts on Quicklink {
  __typename
  quickLinksGroup {
    __typename
    label
    links {
      __typename
      ... on QuicklinkQuickLinksGroupLinksQuickLink {
        label
        brand
        url
      }
      ... on QuicklinkQuickLinksGroupLinksSubGroup {
        label
        links {
          __typename
          ... on QuicklinkQuickLinksGroupLinksSubGroupLinksQuickLink {
            label
            brand
            url
          }
          ... on QuicklinkQuickLinksGroupLinksSubGroupLinksSubGroup {
            label
            links {
              __typename
              ... on QuicklinkQuickLinksGroupLinksSubGroupLinksSubGroupLinksQuickLink {
                label
                brand
                url
              }
              ... on QuicklinkQuickLinksGroupLinksSubGroupLinksSubGroupLinksSubGroup {
                label
                links {
                  __typename
                  ... on QuicklinkQuickLinksGroupLinksSubGroupLinksSubGroupLinksSubGroupLinksQuickLink {
                    label
                    brand
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

fragment MembersParts on Members {
  __typename
  member {
    __typename
    image
    name
    position
    birthday
    hiredDate
  }
}

fragment WorkSchedulesParts on WorkSchedules {
  __typename
  workSchedule {
    __typename
    startDay
    endDay
    schedule
  }
}

fragment ChecklistsParts on Checklists {
  __typename
  checklistGroup {
    __typename
    label
    checklists {
      __typename
      label
      checklist {
        __typename
        label
        notes {
          __typename
          note
        }
      }
    }
  }
}

fragment CarouselAssignmentsParts on CarouselAssignments {
  __typename
  carouselAssignment {
    __typename
    startDay
    endDay
    casinoPoker {
      __typename
      betNJ {
        ... on Members {
          __typename
          member {
            __typename
            image
            name
            position
            birthday
            hiredDate
          }
        }
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
      }
    }
  }
}

fragment UpdatesParts on Updates {
  __typename
  title
  description
  image
  authors {
    __typename
    name
  }
  editors {
    __typename
    name
  }
  slug
  source {
    __typename
    platform
  }
  brands {
    __typename
    brand
  }
  body
}

fragment TeamParts on Team {
  __typename
  qa {
    __typename
    month
    score
  }
}
